import type { Metadata } from "next";
import 'antd/dist/reset.css';
import "./globals.css";
import { Footer } from "./ui/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col bg-black text-white">
          <main className="flex-1">{children}</main>
          <Footer />
      </body>
    </html>
  );
}
